### ISSUE TITLE
Please provide a license

### ISSUE THREAD

**Issue by SiNeumann** [Szmyk/daedalus-vscode#1]
hey, thank you for sharing your extension. I currently try to collect my own snippets and problemmatcher for daedalus in an extension. I'd like to include your syntax checking, so it would great if you would provide a license. I'd usually prefer MIT or BSD style license, but as you are the author it is of course your decision. 
Best regards 
Sigi

**Comment by Szmyk** [comment]
Hi @SiNeumann!

Thank you very much for your interest in my project :heart: 

It's not a big extension, only adding very simple syntax highlighting, but I am very happy that some uses it.

I submitted license text in commit 9a44a8.

**Comment by SiNeumann** [comment]
Thank you for your fast response. I'll share as soon as I have something working.
